const KEY = 'momentum.v001.data';
const today = new Date();
const sports = ['Course','Vélo','Gravel / VTT','Musculation','CrossFit','Hyrox','Natation','Marche','Randonnée','Mobilité / Stretching','Récupération','Ski de fond','Ski alpin','Padel','Repos','Autre'];
const demo = {
  profile:{athlete:'Chris',project:'Momentum',goal:'Marathon octobre 2026 — Sub 3h00',targetDate:'2026-10-18',targetTime:"2h59'59",targetPace:"4'15/km",tagline:"Chaque séance est une pierre de plus sur le chemin vers la ligne de départ."},
  sessions:[
    {date:'2026-06-29',sport:'Course',type:'Endurance',distance:10.2,duration:55,hr:132,rpe:3,comment:'Reprise facile, jambes encore prudentes.'},
    {date:'2026-07-01',sport:'Musculation',type:'Musculation',distance:0,duration:50,hr:0,rpe:5,comment:'Renforcement général, gainage et chaîne postérieure.'},
    {date:'2026-07-03',sport:'Course',type:'Allure marathon',distance:14.1,duration:64,hr:148,rpe:6,comment:'Bloc à allure marathon. Sensations propres, encore à stabiliser.'},
    {date:'2026-07-05',sport:'Vélo',type:'Récupération',distance:42,duration:95,hr:118,rpe:2,comment:'Endurance douce sans impact.'},
    {date:'2026-07-07',sport:'Course',type:'Sortie longue',distance:24.5,duration:132,hr:137,rpe:4,comment:'Sortie longue contrôlée, bonne régularité.'},
    {date:'2026-07-09',sport:'Natation',type:'Récupération',distance:1.8,duration:42,hr:0,rpe:2,comment:'Technique et récupération.'},
    {date:'2026-07-11',sport:'CrossFit',type:'Musculation',distance:0,duration:48,hr:0,rpe:7,comment:'Séance intense, attention à la fatigue résiduelle.'},
    {date:'2026-07-14',sport:'Course',type:'Seuil',distance:13.4,duration:58,hr:154,rpe:7,comment:'3 x 10 minutes au seuil, bonne maîtrise.'}
  ]
};
let state = load(); let charts = {};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||demo}catch{return structuredClone(demo)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmtTime(min){const h=Math.floor(min/60),m=Math.round(min%60);return `${h}h${String(m).padStart(2,'0')}`}
function isoWeek(d){const date=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));date.setUTCDate(date.getUTCDate()+4-(date.getUTCDay()||7));const yearStart=new Date(Date.UTC(date.getUTCFullYear(),0,1));return Math.ceil((((date-yearStart)/86400000)+1)/7)}
function weekKey(s){const d=new Date(s.date+'T12:00:00');return `${d.getFullYear()}-S${String(isoWeek(d)).padStart(2,'0')}`}
function byWeek(){const map={};state.sessions.forEach(s=>{const k=weekKey(s);map[k]??={week:k,km:0,duration:0,load:0,sessions:0,quality:0}; if(s.sport==='Course')map[k].km+=+s.distance||0; map[k].duration+=+s.duration||0; map[k].load+=(+s.duration||0)*(+s.rpe||0); map[k].sessions++; if(['Seuil','VMA','Allure marathon','Sortie longue','Compétition'].includes(s.type))map[k].quality++;});return Object.values(map).sort((a,b)=>a.week.localeCompare(b.week))}
function fitness(weeks){let ctl=35,atl=35;return weeks.map(w=>{ctl=ctl+(w.load-ctl)/42;atl=atl+(w.load-atl)/7;return {...w,ctl:+ctl.toFixed(1),atl:+atl.toFixed(1),tsb:+(ctl-atl).toFixed(1)}})}
function targetProgress(){const p=state.profile;const start=new Date('2026-06-26T12:00:00');const end=new Date(p.targetDate+'T12:00:00');const total=Math.max(1,end-start);const done=Math.min(Math.max(today-start,0),total);return Math.round(done/total*100)}
function renderProfile(){const p=state.profile;document.getElementById('heroTitle').innerHTML=`Mission ${escapeHtml(p.goal.split('—')[0].trim())}<br><span>${escapeHtml((p.goal.split('—')[1]||p.goal).trim())}</span>`;document.getElementById('heroText').textContent=p.tagline;document.getElementById('raceName').textContent=p.goal;document.getElementById('targetTime').textContent=p.targetTime||'—';document.getElementById('targetPace').textContent=p.targetPace||'—';const diff=Math.ceil((new Date(p.targetDate+'T12:00:00')-today)/86400000);document.getElementById('daysLeft').textContent=diff>=0?diff:'objectif passé';const pct=targetProgress();document.getElementById('progressPct').textContent=pct+'%';document.querySelector('.mission-ring').style.setProperty('--progress',pct*3.6+'deg');document.getElementById('healthBar').style.width=pct+'%';document.getElementById('phaseLabel').textContent=pct<35?'Construction':pct<75?'Bloc spécifique':pct<92?'Affûtage':'Semaine course';document.getElementById('healthText').textContent=pct<35?'La priorité est de créer de la régularité sans forcer.':pct<75?'Le cœur de la préparation commence : volume, spécifique et récupération doivent rester en équilibre.':pct<92?'On affine. La fraîcheur devient aussi importante que la forme.':'Le travail est fait. Il reste à arriver frais et confiant.';for(const [k,v] of Object.entries(p)){const el=document.querySelector(`#profileForm [name="${k}"]`);if(el)el.value=v}}
function renderKpis(){const weeks=byWeek();const cur=weeks.at(-1)||{km:0,duration:0,load:0,sessions:0,quality:0};const prev=weeks.at(-2)||{km:0};document.getElementById('kpiKm').textContent=cur.km.toFixed(1)+' km';const delta=cur.km-prev.km;document.getElementById('kpiKmDelta').textContent=(delta>=0?'▲ ':'▼ ')+Math.abs(delta).toFixed(1)+' km vs semaine préc.';document.getElementById('kpiTime').textContent=fmtTime(cur.duration);document.getElementById('kpiLoad').textContent=Math.round(cur.load);document.getElementById('kpiSessions').textContent=cur.sessions;document.getElementById('kpiQuality').textContent=cur.quality+' séance(s) clé(s)'}
function chart(id,type,data,options={}){if(charts[id])charts[id].destroy();charts[id]=new Chart(document.getElementById(id),{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,labels:{boxWidth:10,usePointStyle:true}},tooltip:{mode:'index',intersect:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:'rgba(80,139,180,.12)'}}},...options}})}
function renderCharts(){const weeks=fitness(byWeek()).slice(-12);const labels=weeks.map(w=>w.week);chart('volumeChart','bar',{labels,datasets:[{label:'Km course',data:weeks.map(w=>+w.km.toFixed(1)),borderRadius:8}]});chart('loadChart','line',{labels,datasets:[{label:'Charge',data:weeks.map(w=>Math.round(w.load)),tension:.36,fill:true}]});chart('fitnessChart','line',{labels,datasets:[{label:'CTL',data:weeks.map(w=>w.ctl),tension:.35},{label:'ATL',data:weeks.map(w=>w.atl),tension:.35},{label:'TSB',data:weeks.map(w=>w.tsb),tension:.35}]});const sm={};state.sessions.forEach(s=>sm[s.sport]=(sm[s.sport]||0)+(+s.duration||0));chart('sportChart','doughnut',{labels:Object.keys(sm),datasets:[{label:'Minutes',data:Object.values(sm)}]},{scales:{}})}
function renderInsights(){const weeks=fitness(byWeek());const cur=weeks.at(-1)||{km:0,load:0,tsb:0,quality:0};const prev=weeks.at(-2)||{km:0,load:0};let txt1=cur.km>prev.km?'Le volume progresse. La montée est positive si les sensations restent bonnes.':'Le volume baisse ou se stabilise. Cela peut être une bonne respiration dans la préparation.';let txt2=cur.tsb<-20?'La fatigue estimée est élevée. Une semaine allégée pourrait consolider le bloc.':cur.tsb>10?'La fraîcheur est haute. Bon moment pour placer une séance clé.':'L’équilibre forme/fatigue semble raisonnable.';let txt3=cur.quality>=3?'Beaucoup de séances clés cette semaine : attention à ne pas transformer chaque séance en test.':'La densité qualitative reste maîtrisée.';document.getElementById('insights').innerHTML=[['Volume',txt1],['Fatigue',txt2],['Qualité',txt3]].map(x=>`<article class="insight"><strong>${x[0]}</strong><p>${x[1]}</p></article>`).join('')}
function renderJournal(){const list=[...state.sessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10);document.getElementById('journalList').innerHTML=list.map(s=>`<article class="session-card"><time>${new Date(s.date+'T12:00:00').toLocaleDateString('fr-CH',{weekday:'short',day:'2-digit',month:'short'})}</time><div><h3>${emoji(s.sport)} ${escapeHtml(s.sport)} · ${escapeHtml(s.type)}</h3><p>${(+s.distance||0).toFixed(1)} km · ${fmtTime(+s.duration||0)} · RPE ${s.rpe||'—'} ${s.hr?`· ${s.hr} bpm`:''}</p><p>${escapeHtml(s.comment||'')}</p></div><span class="pill">Load ${Math.round((+s.duration||0)*(+s.rpe||0))}</span></article>`).join('')||'<p>Aucune séance pour le moment.</p>'}
function emoji(s){return {'Course':'🏃','Vélo':'🚴','Gravel / VTT':'🚵','Musculation':'🏋️','CrossFit':'💪','Hyrox':'🔥','Natation':'🏊','Marche':'🚶','Randonnée':'⛰️','Mobilité / Stretching':'🧘','Récupération':'❤️','Ski de fond':'🎿','Ski alpin':'⛷️','Padel':'🎾','Repos':'🌙'}[s]||'✨'}
function escapeHtml(str=''){return String(str).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function renderAll(){renderProfile();renderKpis();renderCharts();renderInsights();renderJournal();save()}
function setup(){document.getElementById('sportSelect').innerHTML=sports.map(s=>`<option>${s}</option>`).join('');document.querySelector('#sessionForm [name=date]').value=new Date().toISOString().slice(0,10);document.getElementById('sessionForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.sessions.push(Object.fromEntries(f.entries()));e.target.reset();document.querySelector('#sessionForm [name=date]').value=new Date().toISOString().slice(0,10);renderAll();location.hash='journal'});document.getElementById('profileForm').addEventListener('submit',e=>{e.preventDefault();state.profile=Object.fromEntries(new FormData(e.target).entries());renderAll();location.hash='mission'});document.getElementById('resetBtn').onclick=()=>{if(confirm('Revenir aux données de démonstration ?')){state=structuredClone(demo);renderAll()}};document.getElementById('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='momentum-data.json';a.click()};document.getElementById('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;state=JSON.parse(await file.text());renderAll()});renderAll()}
setup();
