// A local-only frame gives CSS/media queries an exact viewport when the host browser
// cannot resize its own panel. It shares the real local Supabase session and API.
export function layoutFrame(url) {
 const pages=['index.html','you.html','together.html','progression.html','discover.html','login.html','welcome.html','invite.html','account-deletion-status.html'];
 const requested=url.searchParams.get('page'),page=pages.includes(requested)?requested:'index.html';
 const widths=[320,360,390,430,768,1024,1440],requestedWidth=Number(url.searchParams.get('width'));
 const width=widths.includes(requestedWidth)?requestedWidth:390;
 const landscape=url.searchParams.get('orientation')==='landscape',height=landscape?360:900;
 return `<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recette des formats — MOMENTUM</title><style>body{margin:0;padding:12px;background:#eef0ed;color:#17231d;font:14px system-ui}form{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px}label{display:grid;gap:4px}select,button{font:inherit;padding:8px}#surface{width:100%;overflow:auto}iframe{display:block;border:0;background:white;transform-origin:top left}p{margin:8px 0}</style><form><label>Page<select name="page">${pages.map(p=>`<option${p===page?' selected':''}>${p}</option>`).join('')}</select></label><label>Largeur<select name="width">${widths.map(w=>`<option${w===width?' selected':''}>${w}</option>`).join('')}</select></label><label>Orientation<select name="orientation"><option value="portrait"${!landscape?' selected':''}>Portrait</option><option value="landscape"${landscape?' selected':''}>Paysage</option></select></label><button>Afficher</button></form><p>Recette locale · fenêtre interne de ${width} × ${height} px · comptes fictifs</p><pre id="timings" aria-label="Mesures locales">Chargement…</pre><div id="surface"><iframe id="appFrame" title="Application de recette" src="/${page}" width="${width}" height="${height}"></iframe></div><script>const frame=document.getElementById('appFrame'),surface=document.getElementById('surface');function fit(){const scale=Math.min(1,surface.clientWidth/${width});frame.style.transform='scale('+scale+')';surface.style.height=(${height}*scale)+'px';}addEventListener('resize',fit);fit();frame.addEventListener('load',()=>setTimeout(()=>{const p=frame.contentWindow.performance,n=p.getEntriesByType('navigation')[0],f=p.getEntriesByName('first-contentful-paint')[0];document.getElementById('timings').textContent=JSON.stringify({navigationMs:Math.round(n.duration),domReadyMs:Math.round(n.domContentLoadedEventEnd),firstContentfulPaintMs:f?Math.round(f.startTime):null,resourceCount:p.getEntriesByType('resource').length});},500));</script></html>`;
}
