import * as magick from 'npm:@imagemagick/magick-wasm@0.0.43';
import { DOMParser, XMLSerializer } from 'npm:@xmldom/xmldom@0.9.12';
import { imageCodec } from './image-codec.mjs';
import { createContentValidator } from './content.mjs';
import { createFileIngestHandler } from './handler.mjs';
await magick.initializeImageMagick(await Deno.readFile(new URL(import.meta.resolve('npm:@imagemagick/magick-wasm@0.0.43/magick.wasm'))));
const validateContent=createContentValidator({DOMParser,XMLSerializer,decodeImage:imageCodec(magick)});
const productionOrigin='https://momentum-alpha-rho.vercel.app';
const allowedOrigins=[...(Deno.env.get('MOMENTUM_ALLOWED_ORIGINS')||'').split(','),productionOrigin,'capacitor://localhost'].map(value=>value.trim()).filter(Boolean);
Deno.serve(createFileIngestHandler({url:Deno.env.get('SUPABASE_URL'),serviceKey:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),publishableKey:Deno.env.get('SUPABASE_ANON_KEY'),allowLocal:Deno.env.get('MOMENTUM_LOCAL_DEVELOPMENT')==='true',allowedOrigins,validateContent}));
